//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sales_management_software
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipper
    {
        public string MaShipper { get; set; }
        public string Ten { get; set; }
        public string SoDienThoai { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string MaHD { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
    }
}
