//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sales_management_software
{
    using System;
    using System.Collections.Generic;
    
    public partial class DON_HANG
    {
        public string madh { get; set; }
        public string mahd { get; set; }
        public string makh { get; set; }
        public Nullable<System.DateTime> ngaydat { get; set; }
        public Nullable<System.DateTime> ngaygiao { get; set; }
        public string diachigiao { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual HOA_DON HOA_DON { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
