//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sales_management_software
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLBH_techEntities : DbContext
    {
        public QLBH_techEntities()
            : base("name=QLBH_techEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<lsp_Select_Result> lsp_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lsp_Select_Result>("lsp_Select");
        }
    
        public virtual ObjectResult<NC_NhaCC_Result> NC_NhaCC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NC_NhaCC_Result>("NC_NhaCC");
        }
    
        public virtual int sp_Insert(string maSP, string tenSP, string donGia, string maNCC, string maKho, string maLSP, Nullable<bool> trangThai)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var donGiaParameter = donGia != null ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(string));
    
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var maKhoParameter = maKho != null ?
                new ObjectParameter("MaKho", maKho) :
                new ObjectParameter("MaKho", typeof(string));
    
            var maLSPParameter = maLSP != null ?
                new ObjectParameter("MaLSP", maLSP) :
                new ObjectParameter("MaLSP", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert", maSPParameter, tenSPParameter, donGiaParameter, maNCCParameter, maKhoParameter, maLSPParameter, trangThaiParameter);
        }
    
        public virtual ObjectResult<sp_Select_Result> sp_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Select_Result>("sp_Select");
        }
    
        public virtual int sp_Update(string maSP, string tenSP, string donGia, string maNCC, string maKho, string maLSP, Nullable<bool> trangThai)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var donGiaParameter = donGia != null ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(string));
    
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var maKhoParameter = maKho != null ?
                new ObjectParameter("MaKho", maKho) :
                new ObjectParameter("MaKho", typeof(string));
    
            var maLSPParameter = maLSP != null ?
                new ObjectParameter("MaLSP", maLSP) :
                new ObjectParameter("MaLSP", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update", maSPParameter, tenSPParameter, donGiaParameter, maNCCParameter, maKhoParameter, maLSPParameter, trangThaiParameter);
        }
    
        public virtual ObjectResult<kho_Select_Result> kho_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<kho_Select_Result>("kho_Select");
        }
    }
}
