//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sales_management_software
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIPPER
    {
        public string mashiper { get; set; }
        public string tenshipper { get; set; }
        public string madh { get; set; }
        public string sdt { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual DON_HANG DON_HANG { get; set; }
    }
}
