//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sales_management_software
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONG_SO_KY_THUAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THONG_SO_KY_THUAT()
        {
            this.SAN_PHAM = new HashSet<SAN_PHAM>();
        }
    
        public bool deleted { get; set; }
        public string manhinh { get; set; }
        public string camera { get; set; }
        public string chipset { get; set; }
        public string ram { get; set; }
        public string pin { get; set; }
        public string memory { get; set; }
        public string mats { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAN_PHAM> SAN_PHAM { get; set; }
    }
}
